name: ci

on:
  push:
    branches:
      - 'release'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.0.0

      - uses: actions/checkout@v2
        with:
          fetch-depth: '0' # commit count를 전부 가져와, versionName에 사용하기 위해 필요
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Docker 이미지 이름에는 대문자를 사용할 수 없기 때문에 소문자로 만들어줍니다.
      - name: Obtain uppercased/lowercased pair of a repository name
        id: repo_name_casing
        uses: ASzc/change-string-case-action@v1
        with:
          # github.repository는 "소유자(조직)이름/저장소이름" 형태의 스트링입니다.
          string: ${{ github.repository }}

      - name: Build bootBuildImage with version
        run: ./gradlew bootBuildImage -PdockerImageName=ghcr.io/${{ steps.repo_name_casing.outputs.lowercase }} -PdockerUrl=https://ghcr.io -PdockerUsername=${{ github.repository_owner }} -PdockerPassword=${{ secrets.GITHUB_TOKEN }}
      - name: Build bootBuildImage with latest
        run: ./gradlew bootBuildImage -PdockerImageName=ghcr.io/${{ steps.repo_name_casing.outputs.lowercase }} -PdockerUrl=https://ghcr.io -PdockerUsername=${{ github.repository_owner }} -Ptag=latest -PdockerPassword=${{ secrets.GITHUB_TOKEN }}